import { DependencyDef } from "./types";

export const SPRING_BOOT_VERSIONS = ["3.5.3", "3.4.7", "3.3.12"];

export const JAVA_VERSIONS = ["17", "21"] as const;

export const ARCHFORGE_CODE_FEATURES: DependencyDef[] = [
  {
    id: "jwt",
    label: "JWT Auth & Security",
    description: "Generates SecurityConfig, JwtService, JwtFilter & AuthController with token endpoints",
    icon: "🔑",
    category: "archforge",
    isCodeFeature: true,
    groupId: "io.jsonwebtoken",
    artifactId: "jjwt-api",
  },
  {
    id: "swagger",
    label: "OpenAPI 3 / Swagger UI",
    description: "Generates OpenApiConfig.java + SpringDoc OpenAPI for interactive browser API testing",
    icon: "📖",
    category: "archforge",
    isCodeFeature: true,
    groupId: "org.springdoc",
    artifactId: "springdoc-openapi-starter-webmvc-ui",
  },
  {
    id: "exception-handler",
    label: "Global Exception Handler",
    description: "Generates Centralized @ControllerAdvice REST error response & ResourceNotFoundException",
    icon: "🛡️",
    category: "archforge",
    isCodeFeature: true,
  },
  {
    id: "audit-logging",
    label: "JPA Audit Logging",
    description: "Generates BaseEntity with @CreatedDate/@LastModifiedDate + AuditorAwareImpl",
    icon: "📝",
    category: "archforge",
    isCodeFeature: true,
  },
  {
    id: "docker",
    label: "Docker & Compose Setup",
    description: "Generates production multi-stage Dockerfile, docker-compose.yml & .env.example",
    icon: "🐳",
    category: "archforge",
    isCodeFeature: true,
  },
  {
    id: "flyway",
    label: "Flyway Schema Migrations",
    description: "Generates V1__init.sql schema file for version-controlled database migrations",
    icon: "🚀",
    category: "archforge",
    isCodeFeature: true,
    groupId: "org.flywaydb",
    artifactId: "flyway-core",
  },
  {
    id: "github-actions",
    label: "GitHub Actions CI/CD",
    description: "Generates .github/workflows/ci.yml automated build, test & artifact upload pipeline",
    icon: "⚙️",
    category: "archforge",
    isCodeFeature: true,
  },
];

export const DEPENDENCIES: DependencyDef[] = [
  ...ARCHFORGE_CODE_FEATURES,
  // ── Core Web & Data ────────────────────────────────────────────────────────
  {
    id: "web",
    label: "Spring Web",
    description: "Build web & RESTful apps using Spring MVC and Apache Tomcat",
    icon: "🌐",
    category: "core",
    alwaysIncluded: true,
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-web",
  },
  {
    id: "validation",
    label: "Validation",
    description: "Bean Validation with Hibernate Validator",
    icon: "✅",
    category: "core",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-validation",
  },
  {
    id: "jpa",
    label: "Spring Data JPA",
    description: "Persist data in SQL stores with Hibernate and Spring Data",
    icon: "🗄️",
    category: "core",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-data-jpa",
  },
  {
    id: "data-jdbc",
    label: "Spring Data JDBC",
    description: "Persist data in SQL stores using Spring Data JDBC without ORM overhead",
    icon: "🗄️",
    category: "core",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-data-jdbc",
  },
  {
    id: "lombok",
    label: "Lombok",
    description: "Java annotation library to reduce boilerplate getter/setters",
    icon: "⚡",
    category: "core",
    alwaysIncluded: true,
    groupId: "org.projectlombok",
    artifactId: "lombok",
  },
  {
    id: "actuator",
    label: "Spring Boot Actuator",
    description: "Production-ready health checks, metrics, and monitoring endpoints",
    icon: "📊",
    category: "core",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-actuator",
  },
  {
    id: "webflux",
    label: "Spring Reactive Web (WebFlux)",
    description: "Build reactive, non-blocking web applications with Netty",
    icon: "⚡",
    category: "core",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-webflux",
  },
  {
    id: "cache",
    label: "Spring Cache Abstraction",
    description: "Cache support with @Cacheable annotations",
    icon: "🚀",
    category: "core",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-cache",
  },

  // ── Security & Auth ────────────────────────────────────────────────────────
  {
    id: "security",
    label: "Spring Security",
    description: "Comprehensive authentication and authorization framework",
    icon: "🔐",
    category: "security",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-security",
  },
  {
    id: "oauth2",
    label: "OAuth2 Resource Server",
    description: "OAuth2 / OpenID Connect resource server support",
    icon: "🔒",
    category: "security",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-oauth2-resource-server",
  },

  // ── Database & Caching ────────────────────────────────────────────────────
  {
    id: "postgresql",
    label: "PostgreSQL Driver",
    description: "Production-grade open-source relational database driver",
    icon: "🐘",
    category: "database",
    groupId: "org.postgresql",
    artifactId: "postgresql",
  },
  {
    id: "mysql",
    label: "MySQL Driver",
    description: "JDBC driver for MySQL relational database",
    icon: "🐬",
    category: "database",
    groupId: "com.mysql",
    artifactId: "mysql-connector-j",
  },
  {
    id: "mongodb",
    label: "Spring Data MongoDB",
    description: "NoSQL document-oriented database integration",
    icon: "🍃",
    category: "database",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-data-mongodb",
  },
  {
    id: "redis",
    label: "Spring Data Redis",
    description: "Advanced key-value store and caching with Redis & Lettuce",
    icon: "🔴",
    category: "database",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-data-redis",
  },
  {
    id: "h2",
    label: "H2 Database",
    description: "Fast in-memory database for testing and development",
    icon: "💧",
    category: "database",
    groupId: "com.h2database",
    artifactId: "h2",
  },
  {
    id: "oracle",
    label: "Oracle Driver",
    description: "JDBC driver for Oracle Database",
    icon: "🔴",
    category: "database",
    groupId: "com.oracle.database.jdbc",
    artifactId: "ojdbc11",
  },

  // ── Messaging & Streaming ─────────────────────────────────────────────────
  {
    id: "kafka",
    label: "Spring for Apache Kafka",
    description: "Distributed event streaming and message-driven processing",
    icon: "⚡",
    category: "messaging",
    groupId: "org.springframework.kafka",
    artifactId: "spring-kafka",
  },
  {
    id: "rabbitmq",
    label: "Spring AMQP / RabbitMQ",
    description: "Message queuing and AMQP protocol integration",
    icon: "🐇",
    category: "messaging",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-amqp",
  },

  // ── DevTools & Tooling ────────────────────────────────────────────────────
  {
    id: "devtools",
    label: "Spring Boot DevTools",
    description: "Fast live reloads and auto-restart during development",
    icon: "🛠️",
    category: "devtools",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-devtools",
  },
  {
    id: "mail",
    label: "Java Mail Sender",
    description: "Send email notifications using JavaMail and Spring Mail",
    icon: "✉️",
    category: "devtools",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-mail",
  },
  {
    id: "graphql",
    label: "Spring for GraphQL",
    description: "Build GraphQL APIs with Spring Data & GraphQL Java",
    icon: "🕸️",
    category: "devtools",
    groupId: "org.springframework.boot",
    artifactId: "spring-boot-starter-graphql",
  },
];

export const ARCHITECTURES = [
  {
    id: "layered",
    label: "Layered Architecture",
    description:
      "Classic N-tier: Controller → Service → Repository. Best for standard CRUD applications.",
    icon: "🏗️",
    packages: ["controller", "service", "repository", "entity", "dto", "config"],
  },
  {
    id: "hexagonal",
    label: "Hexagonal Architecture",
    description:
      "Ports & Adapters pattern. Business logic fully isolated from infrastructure.",
    icon: "⬡",
    packages: ["domain", "application/port/in", "application/port/out", "adapter/in/web", "adapter/out/persistence", "config"],
  },
  {
    id: "clean",
    label: "Clean Architecture",
    description:
      "Uncle Bob's Clean Architecture. Dependency inversion from the inside out.",
    icon: "🎯",
    packages: ["domain/entity", "domain/usecase", "domain/repository", "infrastructure", "presentation", "config"],
  },
  {
    id: "modular",
    label: "Modular Monolith",
    description:
      "Feature-based modules. Enforces boundaries without microservice overhead.",
    icon: "📦",
    packages: ["shared", "user", "auth", "notification", "config"],
  },
];
